name       : ecwolf
version    : 1.3.3
release    : 2
source     :
    - https://bitbucket.org/ecwolf/ecwolf/get/1.3.3.tar.gz : ecf1b97ac479229c04f78c32da2b43b2a43429838be712882bb392ec9db300a9
license    :
    - BSD-3-Clause
    - GPL-2.0-or-later
component  : games.action
summary    : ECWolf is a port of the Wolfenstein 3D engine based of Wolf4SDL
description: |
    ECWolf is a port of the Wolfenstein 3D engine based of Wolf4SDL. It combines the original Wolfenstein 3D engine with the user experience of ZDoom to create the most user and mod author friendly Wolf3D source port.
    Game data must be placed in ~/.config/ecwolf/.
optimize   : speed
builddeps  :
    - pkgconfig(SDL_mixer)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libjpeg)
    - bzip2-devel
    - imagemagick
setup      : |
    %cmake_ninja -DGPL=ON
build      : |
    %ninja_build
install    : |
    install -Dm00755 solusBuildDir/ecwolf $installdir/usr/share/ecwolf/ecwolf
    install -Dm00644 solusBuildDir/ecwolf.pk3 $installdir/usr/share/ecwolf/ecwolf.pk3
    install -dm00644 $installdir/usr/bin/
    ln -s /usr/share/ecwolf/ecwolf $installdir/usr/bin/ecwolf

    install -dm00644 $installdir/usr/share/pixmaps
    convert src/win32/icon.ico[0] $installdir/usr/share/pixmaps/wolfenstein.png
    install -Dm00644 $pkgfiles/ecwolf.desktop $installdir/usr/share/applications/ecwolf.desktop
