name       : ecwolf
version    : 1.4.1
release    : 5
source     :
    - https://bitbucket.org/ecwolf/ecwolf/get/8cf8d23a6da3bc0f21a03bf8bb6efadd613902f4.tar.bz2 : dc59bfe3723470669439238af8d3f0bdf1b85288cd77a175c5e0c57e15af9d6e
license    :
    - BSD-3-Clause
    - GPL-2.0-or-later
component  : games.action
homepage   : https://maniacsvault.net/ecwolf/
summary    : Advanced source port of the Wolfenstein 3D engine
description: |
    Provides enhanced game engine for playing Wolfenstein 3D, Spear of Destiny, and Super 3-D Noah's Ark. Requires the original game data files.
    Game data must be placed in ~/.config/ecwolf/.
optimize   : speed
builddeps  :
    - pkgconfig(SDL2_mixer)
    - pkgconfig(SDL2_net)
    - pkgconfig(bzip2)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libjpeg)
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-usr-bin-for-ecwolf-binary.patch
    %cmake_ninja -DGPL=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rfv $installdir/usr/share/doc/
