name       : ecwolf
version    : 1.3.3
release    : 1
source     :
    - https://bitbucket.org/ecwolf/ecwolf/get/1.3.3.tar.gz : 6294ec15f0ae0081c64d6667e3d945dfdf6840708289d3f79738ae89e40763b3
license    : GPL-2.0-or-later
component  : games.action
summary    : ECWolf is a port of the Wolfenstein 3D engine based of Wolf4SDL
description: |
    ECWolf is a port of the Wolfenstein 3D engine based of Wolf4SDL. It combines the original Wolfenstein 3D engine with the user experience of ZDoom to create the most user and mod author friendly Wolf3D source port.
    Game data must be placed in ~/.config/ecwolf/.
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libjpeg)
    - pkgconfig(SDL_mixer)
    - bzip2-devel
    - imagemagick
setup      : |
    %cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/share/ecwolf/ -DGPL=ON
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 ecwolf.pk3 $installdir/usr/share/ecwolf/bin/ecwolf.pk3

    install -d $installdir/usr/share/pixmaps
    convert src/win32/icon.ico[0] $installdir/usr/share/pixmaps/ecwolf.png

    install -d $installdir/usr/bin/
    ln -s /usr/share/ecwolf/bin/ecwolf $installdir/usr/bin/ecwolf
    install -Dm00644 $pkgfiles/ecwolf.desktop $installdir/usr/share/applications/ecwolf.desktop